$(document).ready(() => {

  $('.butt80').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeIn();
    $('#soWhite').fadeOut();
  })
  $('.butt81').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeIn('slow');
    $('#none').fadeOut();
    $('#soWhite').fadeOut();
  })
  $('.butt82').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeIn('slow');
    $('.precious').fadeIn('slow');
    $('.invictus').fadeIn('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeOut();
    $('#soWhite').fadeOut();
  })
  $('.butt83').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeIn();
    $('#soWhite').fadeOut();
  })
  $('.butt84').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeIn();
    $('#soWhite').fadeOut();
  })
  $('.butt85').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeIn('slow');
    $('.flight').fadeIn('slow');
    $('.beasts').fadeIn('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeOut();
    $('#soWhite').fadeOut();
  })
  $('.butt86').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeIn('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeOut();
    $('#soWhite').fadeOut();
  })
  $('.butt87').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeIn('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeOut();
    $('#soWhite').fadeOut();
  })
  $('.butt88').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeOut();
    $('#soWhite').fadeIn();
  })
  $('.butt89').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeIn('slow');
    $('.fences').fadeIn('slow');
    $('.hidden').fadeIn('slow');
    $('.lion').fadeIn('slow');
    $('.loving').fadeIn('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeOut();
    $('#soWhite').fadeOut();
  })
  $('.butt90').on('click', () => {
    $('.shape').fadeIn('slow');
    $('.getout').fadeIn('slow');
    $('.roman').fadeIn('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
    $('#none').fadeOut();
    $('#soWhite').fadeOut();
  })
  $('.buttPicture').on('click', () => {
    $('.shapes').fadeIn('slow');
    $('.getout').fadeIn('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeIn('slow');
    $('.fences').fadeIn('slow');
    $('.hidden').fadeIn('slow');
    $('.lion').fadeIn('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeIn('slow');
    $('.twelve').fadeIn('slow');
    $('.life').fadeIn('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeIn('slow');
    $('.blind').fadeIn('slow');
    $('.precious').fadeIn('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeIn('slow');
  })
  $('.buttDirector').on('click', () => {
    $('.shape').fadeIn('slow');
    $('.getout').fadeIn('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeIn('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeIn('slow');
    $('.life').fadeIn('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeIn('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeIn('slow');
  })
  $('.buttActor').on('click', () => {
    $('.shape').fadeIn('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeIn('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeIn('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeOut('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeIn('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeIn('slow');
    $('.beasts').fadeOut('slow');
    $('.help').fadeOut('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeOut('slow');
    $('.invictus').fadeIn('slow');
    $('.slumdog').fadeOut('slow');
  })
  $('.buttActress').on('click', () => {
    $('.shape').fadeOut('slow');
    $('.getout').fadeOut('slow');
    $('.roman').fadeOut('slow');
    $('.moon').fadeOut('slow');
    $('.fences').fadeOut('slow');
    $('.hidden').fadeOut('slow');
    $('.lion').fadeOut('slow');
    $('.loving').fadeIn('slow');
    $('.selma').fadeOut('slow');
    $('.twelve').fadeOut('slow');
    $('.life').fadeOut('slow');
    $('.flight').fadeOut('slow');
    $('.beasts').fadeIn('slow');
    $('.help').fadeIn('slow');
    $('.blind').fadeOut('slow');
    $('.precious').fadeIn('slow');
    $('.invictus').fadeOut('slow');
    $('.slumdog').fadeOut('slow');
  })
  $('.buttAll').on('click', () => {
    $('.shape').fadeIn('slow');
    $('.getout').fadeIn('slow');
    $('.roman').fadeIn('slow');
    $('.moon').fadeIn('slow');
    $('.fences').fadeIn('slow');
    $('.hidden').fadeIn('slow');
    $('.lion').fadeIn('slow');
    $('.loving').fadeIn('slow');
    $('.selma').fadeIn('slow');
    $('.twelve').fadeIn('slow');
    $('.life').fadeIn('slow');
    $('.flight').fadeIn('slow');
    $('.beasts').fadeIn('slow');
    $('.help').fadeIn('slow');
    $('.blind').fadeIn('slow');
    $('.precious').fadeIn('slow');
    $('.invictus').fadeIn('slow');
    $('.slumdog').fadeIn('slow');
  })
})
